# Generated by Django 5.0 on 2023-12-11 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='logmessage',
            name='cname',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='logmessage',
            name='name',
            field=models.CharField(default='', max_length=50),
        ),
    ]
